language: python
python:
  - '3.6'

install: pip install tox-travis
script: tox

stages:
  - lint
# - test
jobs:
  include:
    - { stage: lint, python: 3.6, env: TOXENV=flake8 }
    - { stage: lint, python: 3.6, env: TOXENV=pylint }
